#x0 z0
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=0,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x1 z0
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=1,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x2 z0
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=2,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x3 z0
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=3,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x4 z0
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=4,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x5 z0
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=5,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
#x6 z0
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=6,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
#x7 z0
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=7,z=0}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
#x0 z1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=0,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x1 z1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=1,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="9"] a 1
#x2 z1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=2,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x3 z1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=3,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x4 z1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=4,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="9"] a 1
#x5 z1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=5,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
#x6 z1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=6,z=1}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x7 z1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=7,z=1}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
#x0 z2
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=0,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x1 z2
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=1,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="9"] a 1
#x2 z2
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=2,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="9"] a 1
#x3 z2
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=3,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x4 z2
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:black_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=4,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x5 z2
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=5,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x6 z2
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=6,z=2}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x7 z2
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=7,z=2}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
#x0 z3
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=0,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
#x1 z3
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=1,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x2 z3
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=2,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x3 z3
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=3,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x4 z3
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=4,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x5 z3
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=5,z=3}] at @s if block ~ ~ ~ minecraft:gray_concrete run scoreboard players add @e[name="9"] a 1
#x6 z3
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=6,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
#x7 z3
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="0"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="1"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="2"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="3"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="4"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="5"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="6"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="7"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="8"] a 1
execute as @e[name=test,scores={x=7,z=3}] at @s if block ~ ~ ~ minecraft:white_concrete run scoreboard players add @e[name="9"] a 1
