execute as @e[name=qr_main,scores={qr_prg=12}] as @e[name=qr_xor] at @s positioned ^^^31.5 rotated as @e[name=qr_xor_1] positioned ^^^16 rotated as @e[name=qr_xor_1] positioned ^^^8 rotated as @e[name=qr_xor_1] positioned ^^^4 rotated as @e[name=qr_xor_1] positioned ^^^2 rotated as @e[name=qr_xor_1] positioned ^^^1 rotated as @e[name=qr_xor_1] positioned ^^^0.5 if block ~~~-2 minecraft:air [] run setblock ~~~-2 minecraft:white_concrete

execute as @e[name=qr_main,scores={qr_prg=12}] as @e[name=qr_xor] at @s positioned ^^^31.5 rotated as @e[name=qr_xor_1] positioned ^^^16 rotated as @e[name=qr_xor_1] positioned ^^^8 rotated as @e[name=qr_xor_1] positioned ^^^4 rotated as @e[name=qr_xor_1] positioned ^^^2 rotated as @e[name=qr_xor_1] positioned ^^^1 rotated as @e[name=qr_xor_1] positioned ^^^0.5 if block ~~~-2 minecraft:white_concrete [] if block ~~~-4 minecraft:white_concrete [] run setblock ~~~ minecraft:white_concrete

execute as @e[name=qr_main,scores={qr_prg=12}] as @e[name=qr_xor] at @s positioned ^^^31.5 rotated as @e[name=qr_xor_1] positioned ^^^16 rotated as @e[name=qr_xor_1] positioned ^^^8 rotated as @e[name=qr_xor_1] positioned ^^^4 rotated as @e[name=qr_xor_1] positioned ^^^2 rotated as @e[name=qr_xor_1] positioned ^^^1 rotated as @e[name=qr_xor_1] positioned ^^^0.5 if block ~~~-2 minecraft:black_concrete [] if block ~~~-4 minecraft:black_concrete [] run setblock ~~~ minecraft:white_concrete

execute as @e[name=qr_main,scores={qr_prg=12}] as @e[name=qr_xor] at @s positioned ^^^31.5 rotated as @e[name=qr_xor_1] positioned ^^^16 rotated as @e[name=qr_xor_1] positioned ^^^8 rotated as @e[name=qr_xor_1] positioned ^^^4 rotated as @e[name=qr_xor_1] positioned ^^^2 rotated as @e[name=qr_xor_1] positioned ^^^1 rotated as @e[name=qr_xor_1] positioned ^^^0.5 if block ~~~-2 minecraft:white_concrete [] if block ~~~-4 minecraft:black_concrete [] run setblock ~~~ minecraft:black_concrete

execute as @e[name=qr_main,scores={qr_prg=12}] as @e[name=qr_xor] at @s positioned ^^^31.5 rotated as @e[name=qr_xor_1] positioned ^^^16 rotated as @e[name=qr_xor_1] positioned ^^^8 rotated as @e[name=qr_xor_1] positioned ^^^4 rotated as @e[name=qr_xor_1] positioned ^^^2 rotated as @e[name=qr_xor_1] positioned ^^^1 rotated as @e[name=qr_xor_1] positioned ^^^0.5 if block ~~~-2 minecraft:black_concrete [] if block ~~~-4 minecraft:white_concrete [] run setblock ~~~ minecraft:black_concrete

execute as @e[name=qr_main,scores={qr_prg=12}] as @e[name=qr_xor] at @s run tp @s ~~1~
execute as @e[name=qr_main,scores={qr_prg=12}] as @e[name=qr_xor] at @s if block ~~~-4 minecraft:air [] run scoreboard players set @e[name=qr_main,scores={qr_prg=12}] qr_prg 13
