execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=1}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 0
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=2}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 17
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=3}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 60
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=4}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 79
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=5}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 50
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=6}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 61
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=7}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 163
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=8}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 26
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=9}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 187
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=10}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 202
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=11}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 180
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=12}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 221
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=13}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 225
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=14}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 83
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=15}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 239
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=16}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 156
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=17}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 164
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=18}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 212
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=19}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 212
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=20}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 188
execute as @e[name=qr_decode_place] if score mode qr_uid matches 4 at @s[scores={qr_encode_l=21}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 190
