execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=1}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 0
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=2}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 173
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=3}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 125
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=4}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 158
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=5}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 2
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=6}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 103
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=7}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 182
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=8}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 118
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=9}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 17
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=10}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 145
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=11}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 201
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=12}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 111
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=13}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 28
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=14}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 165
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=15}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 53
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=16}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 161
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=17}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 21
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=18}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 245
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=19}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 142
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=20}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 13
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=21}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 102
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=22}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 48
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=23}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 227
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=24}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 153
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=25}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 145
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=26}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 218
execute as @e[name=qr_decode_place] if score mode qr_uid matches 5 at @s[scores={qr_encode_l=27}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 70
